# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'payup_mobile' do
  pod 'Stripe', '~> 14.0.0'
  inherit! :search_paths

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


end
